-- GENERATED from src/data/menu-baseline.json; see recovery/README.md.
-- Only for an EMPTY menu with the current schema. Not a live synchronization script.
CREATE TABLE _menu_recovery_guard (ok INTEGER CHECK (ok = 1));
INSERT INTO _menu_recovery_guard SELECT CASE WHEN
  (SELECT COUNT(*) FROM categories) = 0 AND (SELECT COUNT(*) FROM items) = 0
  THEN 1 ELSE 0 END;
INSERT INTO categories (id, name, sort, subtitle, note) VALUES
(1, 'Appetizers', 0, '', ''),
(2, 'Baskets', 1, '', ''),
(3, 'Sandwiches', 2, '', ''),
(4, 'Burgers', 3, '', ''),
(5, 'Wraps', 4, '', ''),
(6, 'Pizzas', 5, '', ''),
(7, 'Salads', 6, '', ''),
(8, 'Loaded Tot Baskets', 7, '', ''),
(9, 'On The Lighter Side', 8, '', ''),
(10, 'Mexican Night', 9, 'Tuesdays · 5–10 PM', 'Chicken substitution available · Nacho cheese, queso and shredded-cheese substitutions available');
INSERT INTO items (id, category_id, name, description, sort, active, photo_key, late_night, photo_orientation) VALUES
(1, 1, 'French Fries', '', 0, 1, NULL, 1, 'portrait'),
(2, 1, 'Tator Tots', '', 1, 1, NULL, 1, 'portrait'),
(3, 1, 'Waffle Fries', '', 2, 1, NULL, 1, 'portrait'),
(4, 1, 'Beer Fries', '', 3, 1, NULL, 1, 'portrait'),
(5, 1, 'Sweet Potato Fries', '', 4, 1, NULL, 1, 'portrait'),
(6, 1, 'Onion Rings', '', 5, 1, NULL, 1, 'portrait'),
(7, 1, 'Funnel Cake Fries', '', 6, 1, NULL, 1, 'portrait'),
(8, 1, 'Mozzarella Sticks', '', 7, 1, NULL, 1, 'portrait'),
(9, 1, '6 Drummies', '', 8, 1, NULL, 1, 'portrait'),
(10, 1, '8 Mini Corn Dogs', '', 9, 1, NULL, 1, 'portrait'),
(11, 1, 'Big Pretzel', '', 10, 1, 'menu/11/8cbf0832-7bc3-4492-be63-2f434056d13d.webp', 1, 'square'),
(12, 1, 'Jalapeno Poppers', '', 11, 1, NULL, 1, 'portrait'),
(14, 1, 'Battered Mushrooms', '', 13, 1, NULL, 1, 'portrait'),
(15, 1, 'Mini Tacos', '', 14, 1, NULL, 1, 'portrait'),
(16, 1, 'Broccoli Bites', '', 15, 1, NULL, 1, 'portrait'),
(17, 1, '4 Chicken Strips', '', 16, 1, NULL, 1, 'portrait'),
(18, 1, 'Mac & Cheese Bites', '', 17, 1, NULL, 1, 'portrait'),
(19, 1, 'Deep Fried Pickles', '', 18, 1, NULL, 1, 'portrait'),
(82, 1, 'Cheesy Jalapeno Potato Bites', NULL, 200, 1, NULL, 1, 'portrait'),
(83, 1, 'Cheese Bombs', 'Garlic or ghost pepper.', 210, 1, NULL, 1, 'portrait'),
(84, 1, 'Breadsticks', NULL, 220, 1, NULL, 0, 'portrait'),
(85, 1, 'Choice of any 3 Appetizers', 'Choose any three appetizers (limit one Drummies).', 230, 1, NULL, 1, 'portrait'),
(86, 1, 'Egg Rolls', NULL, 240, 1, NULL, 1, 'portrait'),
(112, 1, 'Cheese Curds', 'White, Yellow or Jalapeño ', 241, 1, NULL, 1, 'portrait'),
(20, 2, 'Drummie Basket', 'Served with French fries & toast.', 0, 1, NULL, 0, 'portrait'),
(21, 2, 'Jumbo Shrimp Basket', 'Served with French fries & toast.', 1, 1, NULL, 0, 'portrait'),
(22, 2, 'Chicken Strip Basket', 'Served with French fries & toast.', 2, 1, NULL, 0, 'portrait'),
(87, 2, 'Fish Basket', 'Served with French fries & toast.', 200, 1, NULL, 0, 'portrait'),
(23, 3, 'Chicken Sandwich', 'Lettuce and mayo.', 0, 1, NULL, 0, 'portrait'),
(24, 3, 'Chicken Bacon Swiss', 'Bacon and Swiss cheese.', 1, 1, NULL, 0, 'portrait'),
(25, 3, 'Buffalo Chicken', 'Lettuce, tomato, bleu cheese, buffalo sauce.', 2, 1, NULL, 0, 'portrait'),
(26, 3, 'Hawaiian Chicken', 'Ham, grilled pineapple, Swiss cheese.', 3, 1, NULL, 0, 'portrait'),
(27, 3, 'Bacon Chicken Ranch', 'Bacon, pepper jack cheese, ranch dressing.', 4, 1, NULL, 0, 'portrait'),
(28, 3, 'Honey Mustard Chicken', 'Lettuce, Swiss cheese, honey mustard dressing.', 5, 1, NULL, 0, 'portrait'),
(29, 3, 'Chicken Cordon Bleu', 'Ham and Swiss cheese.', 6, 1, NULL, 0, 'portrait'),
(30, 3, 'Chicken Chipotle', 'Bacon, lettuce, cheddar cheese, onion, tomato, chipotle ranch.', 7, 1, NULL, 0, 'portrait'),
(31, 3, 'Grayz''n Chicken', 'Ham, cheddar and Swiss cheese, BBQ sauce.', 8, 1, NULL, 0, 'portrait'),
(32, 3, 'Fish Sandwich', 'Lettuce, cheddar cheese, tartar sauce.', 9, 1, NULL, 0, 'portrait'),
(33, 3, 'Philly Cheese', 'Onion, green peppers, mushrooms, choice of beef or chicken.', 10, 1, 'menu/33/d6d91de0-83ee-4c0f-9a59-e1eb66ed1f4c.webp', 0, 'square'),
(88, 3, 'BLT', 'Bacon, lettuce, tomato, mayo. Triple decker or Texas toast.', 200, 1, NULL, 0, 'portrait'),
(89, 3, 'Reuben', 'Corned beef, sauerkraut, Swiss cheese and thousand island dressing on marble rye.', 210, 1, NULL, 0, 'portrait'),
(90, 3, 'Club', 'Bacon, turkey, ham, lettuce, tomato, Swiss cheese and mayo. Triple decker or Texas toast.', 220, 1, NULL, 0, 'portrait'),
(91, 3, 'Gyro Sandwich', 'Beef and lamb meat, lettuce, tomato, onion, cucumbers, feta cheese and tzatziki sauce.', 230, 1, NULL, 0, 'portrait'),
(92, 3, 'Garlic Turkey Bacon Sub', 'Turkey, bacon, cheddar cheese, lettuce, tomato, onion, garlic spread and choice of ranch or honey mustard on a hoagie bun.', 240, 1, NULL, 0, 'portrait'),
(34, 4, 'Hamburger', '', 0, 1, NULL, 1, 'portrait'),
(35, 4, 'Cheeseburger', '', 1, 1, NULL, 1, 'portrait'),
(36, 4, 'Double Cheeseburger', '', 2, 1, NULL, 1, 'portrait'),
(37, 4, 'Mushroom Swiss', '', 3, 1, 'menu/37/aac954e5-59a2-4863-b024-7f5f0448a452.webp', 0, 'landscape'),
(38, 4, 'Bacon Cheeseburger', '', 4, 1, 'menu/38/8927c7c7-7209-4bca-b818-ce50c75a7308.webp', 1, 'landscape'),
(39, 4, 'California Burger', '', 5, 1, NULL, 0, 'portrait'),
(40, 4, 'Patty Melt', '', 6, 1, NULL, 0, 'portrait'),
(41, 4, 'Pizza Burger', 'Pepperoni, mozzarella cheese, pizza sauce.', 7, 1, NULL, 0, 'portrait'),
(42, 4, 'Stampede Burger', 'Bacon, mushrooms, pepper jack cheese, horseradish sauce.', 8, 1, NULL, 0, 'portrait'),
(43, 4, 'Grayz''n Burger', 'Ham, cheddar and Swiss cheese, BBQ sauce.', 9, 1, NULL, 0, 'portrait'),
(44, 4, 'The G Mac', 'Lettuce, onion, pickles, thousand island dressing.', 10, 1, NULL, 0, 'portrait'),
(45, 4, 'Dovi Burger', 'Cheddar cheese, BBQ sauce.', 11, 1, NULL, 0, 'portrait'),
(46, 4, 'Bleu Cheese Burger', 'Bacon, fried onions, pepper jack cheese, bleu cheese dressing.', 12, 1, NULL, 0, 'portrait'),
(47, 4, 'Olive Burger', 'Green olives and Swiss cheese.', 13, 1, 'menu/47/73e6a9cf-5f2d-4a6f-9764-2ddc4ee894d8.webp', 0, 'landscape'),
(74, 4, 'Southwest Burger', 'Jalapeno poppers, pepper jack cheese, chipotle ranch', 14, 1, NULL, 0, 'portrait'),
(93, 4, 'Western Burger', 'Onion rings, cheddar cheese, BBQ sauce.', 200, 1, NULL, 0, 'portrait'),
(94, 4, 'German Burger', 'Sauerkraut and Swiss cheese.', 210, 1, NULL, 0, 'portrait'),
(95, 4, 'Hangover Burger', 'Bacon, fried egg, cheddar cheese.', 220, 1, NULL, 0, 'portrait'),
(96, 4, 'Jalapeno Burger', 'Jalapeno poppers and pepper jack cheese.', 230, 1, NULL, 0, 'portrait'),
(48, 5, 'Chicken Bacon Ranch', 'Bacon, lettuce, cheddar cheese, ranch dressing.', 0, 1, NULL, 0, 'portrait'),
(49, 5, 'Chicken Caesar', 'Lettuce, onion, tomato, parmesan cheese, Caesar dressing.', 1, 1, NULL, 0, 'portrait'),
(50, 5, 'Philly Cheese', 'Onion, green peppers, mushrooms, choice of beef or chicken.', 2, 1, NULL, 0, 'portrait'),
(51, 5, 'BLT', 'Bacon, lettuce, tomato, mayo.', 3, 1, NULL, 0, 'portrait'),
(97, 5, 'Turkey Bacon', 'Turkey, bacon, lettuce, Swiss cheese and mayo.', 200, 1, NULL, 0, 'portrait'),
(98, 5, 'Hawaiian BBQ Chicken', 'Ham, lettuce, pineapple, Swiss cheese and BBQ sauce.', 210, 1, NULL, 0, 'portrait'),
(99, 5, 'Chipotle Chicken Bacon Ranch', 'Bacon, lettuce, onion, tomato, cheddar cheese and chipotle ranch dressing.', 220, 1, NULL, 0, 'portrait'),
(100, 5, 'Buffalo Chicken', 'Lettuce, tomato, cheddar cheese, bleu cheese and hot sauce.', 230, 1, NULL, 0, 'portrait'),
(52, 6, 'Cheese', '', 0, 1, NULL, 1, 'portrait'),
(53, 6, 'Sausage & Pepperoni', '', 1, 1, NULL, 1, 'portrait'),
(54, 6, 'Hawaiian', 'Canadian bacon, pineapple.', 2, 1, NULL, 0, 'portrait'),
(55, 6, 'Meat', 'Sausage, pepperoni, Canadian bacon, beef, bacon.', 3, 1, NULL, 1, 'portrait'),
(56, 6, 'Deluxe', 'Sausage, pepperoni, mushroom, onion, green pepper.', 4, 1, NULL, 0, 'portrait'),
(57, 6, 'Veggie', 'Mushroom, onion, green pepper, tomato, green & black olives.', 5, 1, NULL, 0, 'portrait'),
(58, 6, 'BBQ Chicken', 'BBQ sauce, bacon, chicken, onion.', 6, 1, NULL, 0, 'portrait'),
(59, 6, 'Taco', 'Taco meat, onion, mozzarella & cheddar, tomato, black olives, lettuce.', 7, 1, NULL, 0, 'portrait'),
(60, 6, 'Chicken Alfredo', 'Alfredo sauce, chicken, onion.', 8, 1, NULL, 0, 'portrait'),
(61, 6, 'Bacon Cheeseburger', 'Beef, bacon, mozzarella & cheddar cheese, pickles.', 9, 1, NULL, 0, 'portrait'),
(62, 6, 'Supreme', 'Beef, sausage, bacon, onions, green peppers, mushrooms, green & black olives.', 10, 1, NULL, 0, 'portrait'),
(63, 6, 'Pizza Fries', '', 11, 1, NULL, 1, 'portrait'),
(101, 6, 'Buffalo Chicken', 'Buffalo sauce, chicken, bleu cheese crumbles.', 200, 1, NULL, 0, 'portrait'),
(102, 6, 'Chicken Bacon Ranch', 'Ranch dressing, chicken, bacon.', 210, 1, NULL, 0, 'portrait'),
(103, 6, 'Reuben', 'Thousand island dressing, corned beef, sauerkraut.', 220, 1, NULL, 0, 'portrait'),
(104, 6, 'Philly Cheesesteak', 'Cheese sauce, Philly meat, green peppers, onions, mushrooms.', 230, 1, NULL, 0, 'portrait'),
(105, 6, 'Gyro', 'Beef and lamb meat, onion, tomato, cucumber, feta cheese and tzatziki sauce on the side.', 240, 1, NULL, 0, 'portrait'),
(64, 7, 'Side Salad', 'Tomato, onion, cucumber, green pepper, cheddar cheese, hard-boiled egg.', 0, 1, NULL, 0, 'portrait'),
(65, 7, 'Chef Salad', 'Ham, turkey, tomato, onion, cucumber, green pepper, cheddar cheese, hard-boiled egg, croutons.', 1, 1, NULL, 0, 'portrait'),
(66, 7, 'Taco Salad', 'Taco meat, tomato, onion, black olives, cheddar cheese.', 2, 1, NULL, 0, 'portrait'),
(67, 7, 'Caesar Salad', 'Chicken, tomato, onion, cucumber, parmesan cheese, hard-boiled egg, croutons, Caesar dressing.', 3, 1, NULL, 0, 'portrait'),
(76, 7, 'Grilled/Crispy Chicken Salad', '', 4, 1, NULL, 0, 'portrait'),
(106, 7, 'Chicken Chipotle Salad', 'Chicken, bacon, tomato, onion, cheddar cheese, chipotle ranch dressing.', 200, 1, NULL, 0, 'portrait'),
(107, 7, 'Gyro Salad', 'Lamb, tomato, onion, cucumber, feta cheese, tzatziki sauce.', 210, 1, 'menu/107/016883f0-aa99-4dd5-a6ec-5a3ef09105d6.webp', 0, 'landscape'),
(108, 7, 'Chicken Cranberry Salad', 'Chicken, cucumber, walnuts, dried cranberries, feta cheese, raspberry vinaigrette.', 220, 1, NULL, 0, 'portrait'),
(109, 7, 'Hawaiian Chicken Salad', 'Chicken, ham, pineapple, cucumber, parmesan, BBQ or mango habanero.', 230, 1, NULL, 0, 'portrait'),
(68, 8, 'Philly Tots', 'Tots, philly meat, onion, mushrooms, green peppers, nacho cheese.', 0, 1, NULL, 0, 'portrait'),
(69, 8, 'Taco Tots', 'Tots, taco meat, onion, tomato, black olives, nacho cheese.', 1, 1, NULL, 0, 'portrait'),
(110, 8, 'Chicken Bacon Ranch Tots', 'Tots, chicken, bacon, ranch and nacho cheese sauce.', 200, 1, NULL, 0, 'portrait'),
(70, 9, '1 Grilled Cheese & French Fries', '', 0, 1, NULL, 0, 'portrait'),
(120, 9, '2 Grilled Cheese & French Fries', '', 1, 1, NULL, 0, 'portrait'),
(71, 9, '2 Chicken Strips & French Fries', '', 2, 1, NULL, 0, 'portrait'),
(121, 9, '5 Mini Corn Dogs & French Fries', '', 3, 1, NULL, 0, 'portrait'),
(72, 9, 'Chicken Quesadilla', '', 4, 1, NULL, 0, 'portrait'),
(122, 9, 'Lite Salad', 'Any Salad, See Salads', 5, 1, NULL, 0, 'portrait'),
(113, 10, '2 Soft Shell', 'Meat, shredded cheese, lettuce, onion, tomato, and black olives.', 0, 1, NULL, 0, 'portrait'),
(114, 10, 'Burrito', 'Meat, refried beans, shredded cheese, lettuce, onion, and tomato rolled up in a tortilla. Topped with shredded cheese, black olives, and enchilada sauce.', 1, 1, NULL, 0, 'portrait'),
(115, 10, 'Chimichanga', 'Meat, refried beans, shredded cheese, and onion rolled up in a tortilla and fried. Topped with enchilada sauce, black olives, and shredded cheese. Lettuce and tomato on the side.', 2, 1, NULL, 0, 'portrait'),
(116, 10, 'Enchilada', 'Meat, refried beans, shredded cheese, and onion rolled up in a tortilla. Topped with enchilada sauce, black olives, and shredded cheese. Lettuce and tomato on the side.', 3, 1, NULL, 0, 'portrait'),
(117, 10, 'Nacho Deluxe', 'Meat, lettuce, onion, tomato, black olives, and nacho cheese served on top of chips.', 4, 1, NULL, 0, 'portrait'),
(118, 10, 'Taco Salad', 'Meat, shredded cheese, lettuce, onion, tomato, and black olives served in a shell bowl.', 5, 1, NULL, 0, 'portrait'),
(119, 10, 'Chips & Salsa or Chips & Cheese', '', 6, 1, NULL, 0, 'portrait');
DROP TABLE _menu_recovery_guard;
