-- RETIRED: the destructive staging menu seed has been removed.
-- This file intentionally performs no writes.
-- Use recovery/menu-canonical.sql with an EMPTY menu and current schema.
-- See recovery/README.md. Never reseed live production.
